### ISSUE TITLE
spi-stm32.c: dma mode doesn't support cs_change and delay_usecs functionalities

### ISSUE THREAD

**Issue by ederguidsa** [EmcraftSystems/linux-upstream#1]
When using driver spi-stm32.c in dma mode, there is no support to cs_change and delay_usecs.
The function that provides these functionalities is "stm32_spi_transfer_done", which is only used in the interruption handler.

This issue refers to branch "emcraft".

**Comment by ederguidsa** [comment]
Solved by making the following changes:

--- spi-stm32.c	2018-09-13 16:06:20.366003280 -0300
+++ spi-stm32.c	2018-09-13 09:48:19.968505131 -0300
@@ -883,6 +883,7 @@
 	dma_sync_single_for_cpu(dev, dma->buf_dma, dma->len_dma, DMA_FROM_DEVICE);
 	dma_unmap_single(dev, dma->buf_dma, dma->len_dma, DMA_FROM_DEVICE);
 
+	stm32_spi_transfer_done(c);
 	stm32_spi_dma_xf_done(c);
 }
 
@@ -993,6 +994,7 @@
 	dma->dsc = NULL;
 	dma_unmap_single(dev, dma->buf_dma, dma->len_dma, DMA_TO_DEVICE);
 
+	stm32_spi_transfer_done(c);
 	stm32_spi_dma_xf_done(c);
 }

**Comment by ederguidsa** [comment]
Solved by making the changes in the attached file.
[spi-stm32.txt](https://github.com/EmcraftSystems/linux-upstream/files/2380697/spi-stm32.txt)

**Comment by sposelenov-emcraft** [comment]
Hi, your fix looks correct. Did you test it? Thanks!

**Comment by ederguidsa** [comment]
Yes, I've tested it on stm32f429 som module. It has worked ok so far.
